services:
  - type: worker
    name: jd-gfx-access
    runtime: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: SLACK_BOT_TOKEN
        sync: false
      - key: SLACK_APP_TOKEN
        sync: false
      - key: JUMPDESKTOP_API_TOKEN
        sync: false
      - key: JUMPDESKTOP_NY_TEAM_ID
        value: T-01GW30D3R7T1717HTHWYQ7DW45
      - key: JUMPDESKTOP_LA_TEAM_ID
        value: T-01H6VNE44DZDD0C2TVZC1Z4V57
      - key: AUDIT_CHANNEL_ID
        sync: false
